# Generated by Django 2.1.1 on 2018-09-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180921_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='标签',
        ),
        migrations.AddField(
            model_name='tags',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='标签名称'),
        ),
    ]
